### ISSUE TITLE
Raw Data being Overwritten by Processed Files

### ISSUE THREAD

**Issue by pdeperio** [XENON1T/cax#5]
Some example datasets and hosts where the raw data have been overwritten:

Detail for run 211
Run name	160426_1932
Source type	PMT test
login.ci-connect

Detail for run 259
Run name	160428_1825
Source type	PMT test
lena, xe-grid01, tegner

**Comment by JelleAalbers** [comment]
Thanks Patrick, that's a pretty nasty bug ! Turns out the data transfer code did not add `.root` to the location of the processed data files. Fortunately, since it is the transfer code, this bug did not delete the data on all sites. I hope 03811d76802ffe6fe415c88101440c3cf4fbae6d fixes this,thanks to autodeploy we should know soon.

**Comment by JelleAalbers** [comment]
Actually sorry, we have to restart cax on the processing site of course.

**Comment by JelleAalbers** [comment]
Looks like (e.g. run 339) this is resolved, otherwise we can reopen.
