### ISSUE TITLE
TPC runs with errors

### ISSUE THREAD

**Issue by pietrodigangi** [XENON1T/cax#62]
List of TPC runs showing **error at midway-login1** step
since 01 Dec 2016:

Num. Date                        Source  Error

 -- December
4998	1.12.16 at 03:42:13	none      `Pax multiprocessing crashed due to exception in one of the workers.`
5150	6.12.16 at 13:36:43	LED
5152	6.12.16 at 14:06:33	LED
5189 7.12.16 at 15:09:55   Th228
5248 9.12.16 at 12:44:53   none

**Comment by lucrlom** [comment]
run under process:

4805 running
5029 running

**Comment by MAVJ** [comment]
Update on List of TPC runs showing error at midway-login1 step after help of Francesco and Patrick (thank you both):

* Since 23 November 2016:

Num.	       Date 	                                 Source                          
4961              29.11.16 at 14:27:39	         none

* December 2016:

Num.	       Date 	                                 Source                        
4998	1.12.16 at 03:42:13	          none  **
5044	2.12.16 at 14:58:20	         none
5051	2.12.16 at 20:18:59	         none
5119	        5.12.16 at 14:57:16	         Th228
5127	5.12.16 at 19:11:29	         none
5151	6.12.16 at 13:44:24	         LED
5152	6.12.16 at 14:06:33	         LED

** `Pax multiprocessing crashed due to exception in one of the workers.`

**Comment by pdeperio** [comment]
Old version of transfer/processing. 

Also, pax multiprocessing crashes seem to have been fixed.
